### ISSUE TITLE
Filtering by owner - improvement suggestion

### ISSUE THREAD

**Issue by Rdornier** [German-BioImaging/omero-tagsearch#15]
Hi Tom, 

I find very nice the new features introduced in the latest version !
However, I find not so convenient the fact that we need to switch to "all users" to get access to all available tags.

For example, in a read-annotate group, everyone has, by default, access to all the tags (in the autotag, when adding new tags manually...) but this is not anymore the case in the new version of the tag search. By default, you can only filter your tags if your are looking at your data.
I think it could be nice to match the permission level restrictions for the "by-default" behavior (i.e. always look at all the available tags) and to add a drop-drown menu with the list of available owners, in case the users want to restrict tags by owner.

Thanks,
Rémy.

**Comment by Tom-TBT** [comment]
Hi Rémy,
last update indeed introduced a change in the behavior of the plugin. There is one extra step now for the people who were used to searching for tags not belonging to them.

The dropdown list is an interesting idea, but it may interfere UI-wise with the existing dropdown list for the group/user.

I could introduce instead a checkbox to filter yes/no for the currently selected user. Defaults to "no" to restore the previous behavior, and the "user filter" selection still happens in the classic omero-web way.  What do you think?

**Comment by Rdornier** [comment]
Hi Tom, 

Yes indeed, the checkbox is a good idea to tackle this, while keeping the tag filtering by owner as it is currently implemented.
